# Generated by Django 4.1 on 2024-03-06 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catalog",
            fields=[
                ("CatalogID", models.AutoField(primary_key=True, serialize=False)),
                ("CatalogName", models.CharField(max_length=255)),
                ("CatalogDescription", models.TextField(blank=True, null=True)),
                ("CreationDate", models.DateTimeField()),
                ("LastModifiedDate", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                ("DiagnosisID", models.AutoField(primary_key=True, serialize=False)),
                ("DiagnosisCode", models.CharField(max_length=20)),
                (
                    "DiagnosisName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="records.catalog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scoring",
            fields=[
                ("ScoringID", models.AutoField(primary_key=True, serialize=False)),
                ("ProcedureCodes", models.TextField(blank=True, null=True)),
                ("ScoringValue", models.IntegerField()),
                (
                    "Catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="records.catalog",
                    ),
                ),
                (
                    "Diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="records.diagnosis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                ("ProcedureID", models.AutoField(primary_key=True, serialize=False)),
                ("ProcedureCode", models.CharField(max_length=20)),
                (
                    "ProcedureName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="records.catalog",
                    ),
                ),
            ],
        ),
    ]
